import {
  Banknote,
  Baby,
  Bike,
  BookOpen,
  Briefcase,
  Car,
  CircleEllipsis,
  Clapperboard,
  Coffee,
  Dumbbell,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Music,
  PawPrint,
  Phone,
  Plane,
  Repeat,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Utensils,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icon names persisted on categories, mapped to lucide components. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  home: Home,
  zap: Zap,
  car: Car,
  utensils: Utensils,
  clapperboard: Clapperboard,
  "heart-pulse": HeartPulse,
  repeat: Repeat,
  "circle-ellipsis": CircleEllipsis,
  banknote: Banknote,
  coffee: Coffee,
  gift: Gift,
  plane: Plane,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  music: Music,
  "gamepad-2": Gamepad2,
  dumbbell: Dumbbell,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  landmark: Landmark,
  phone: Phone,
  wifi: Wifi,
  wrench: Wrench,
  "paw-print": PawPrint,
  baby: Baby,
  bike: Bike,
  heart: Heart,
  sparkles: Sparkles,
};

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? CircleEllipsis;
}

export const CATEGORY_COLORS = [
  "#10b981",
  "#3b82f6",
  "#eab308",
  "#06b6d4",
  "#f43f5e",
  "#8b5cf6",
  "#ec4899",
  "#f97316",
  "#22c55e",
  "#737373",
  "#0ea5e9",
  "#a855f7",
];
